"""empty message

Revision ID: 6cdcb7f95ff5
Revises: 
Create Date: 2020-05-05 22:13:34.433643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdcb7f95ff5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value1', sa.String(), nullable=True),
    sa.Column('value2', sa.Float(), nullable=True),
    sa.Column('value3', sa.Boolean(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=False),
    sa.Column('lastModificationDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
