"""empty message

Revision ID: f92afa6a0d89
Revises: 
Create Date: 2020-05-06 14:08:44.522928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92afa6a0d89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value1', sa.String(), nullable=True),
    sa.Column('value2', sa.Float(), nullable=True),
    sa.Column('value3', sa.Boolean(), nullable=True),
    sa.Column('creationDate', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('lastModificationDate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
